### ISSUE TITLE
关于Closure参数值传递

### ISSUE THREAD

**Issue by yuinm** [chen3feng/toft#131]
你好：
`   
Closure<R ()>*
NewClosure(Class *object, R (MethodClass::*method)(Arg1), PreArg1&& pa1)
{
 return new MethodClosure_Arg0_Bind1<false, R, Class, MethodClass, Arg1,PreArg1>(object, method, std::forward<PreArg1>(pa1));
}
`
我觉得改成这样没什么问题，可以节约2次拷贝构造，而且如果传入的值是右值的话，最后一次拷贝构造可以变成移动构造 ，这样对于类似标准库的容器，或者支持移动构造的类的支持不是更好嘛？ 
不知道我是否有没想到的地方，有时间请指正一下。

**Comment by chen3feng** [comment]
可以的，不过这是c++98代码，那时候c++11还没有普及。closure生存期管理比较麻烦容易出错，新代码建议尽量用lambda结合std::function之类的，更加安全可读。

**Comment by yuinm** [comment]
哦..好的，多谢了
