### ISSUE TITLE
注释写错了

### ISSUE THREAD

**Issue by yuinm** [chen3feng/toft#132]
https://github.com/chen3feng/toft/blob/c44f8c5616d55d2f5cab46a3dbf8a1e4ad0fb3d2/system/threading/thread.h#L41
 这里注释稍微有点问题， 这里写的是如果已经线程已经stop了，返回true，这里重复join会有问题， 不会返回true， 因为这里没判定那个joinable 啊.

**Comment by chen3feng** [comment]
是的……
