### ISSUE TITLE
recordio 写入失败的情况

### ISSUE THREAD

**Issue by yuinm** [chen3feng/toft#133]
问题：这里如果write出错了直接就返回了， 外面使用的时候如果继续写入"size+内容"的这种格式就被破坏掉了。
想法：如果失败，我想了2种办法，1. 新建文件然后后续内容继续写入新文件。 2.通过write统计刚刚写入的字节数，如果失败通过seek回退刚刚的操作。

我这么想是正确的吗？ 
https://github.com/chen3feng/toft/blob/c44f8c5616d55d2f5cab46a3dbf8a1e4ad0fb3d2/storage/recordio/recordio.cc#L36
![image](https://user-images.githubusercontent.com/13299372/81637658-75513080-9449-11ea-9f5d-4f25325fdeed.png)

**Comment by chen3feng** [comment]
1 显然不合适，2 其实也没那么简单，比如 seek/ftruncate 也可能失败。比较好的方案是加入校验和容错机制，但是会破坏兼容性。

**Comment by yuinm** [comment]
谢谢， 我试试实现一个..
